"""Generate Oxco window/taskbar icons (PNG + ICO). Run from repo root: python scripts/make_oxco_icon.py"""

from __future__ import annotations

import base64
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
SIZES = (16, 24, 32, 48, 64, 128, 256)

BG = (18, 24, 38)
ACCENT = (0, 196, 154)
ACCENT2 = (255, 120, 64)
TEXT = (245, 248, 255)


def _font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for name in ("segoeuib.ttf", "arialbd.ttf", "calibrib.ttf"):
        try:
            return ImageFont.truetype(name, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


def render_icon(size: int) -> Image.Image:
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    pad = max(2, size // 16)
    draw.rounded_rectangle(
        (pad, pad, size - pad - 1, size - pad - 1),
        radius=max(4, size // 5),
        fill=BG,
        outline=ACCENT,
        width=max(1, size // 32),
    )
    inner = pad + max(2, size // 10)
    draw.rounded_rectangle(
        (inner, inner + size // 6, size - inner, size - inner - size // 10),
        radius=max(3, size // 8),
        fill=(28, 36, 54),
    )
    font = _font(max(10, int(size * 0.34)))
    label = "Ox"
    bbox = draw.textbbox((0, 0), label, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    tx = (size - tw) // 2
    ty = (size - th) // 2 - max(1, size // 20)
    draw.text((tx, ty), label, font=font, fill=TEXT)
    bar_y = size - inner - max(2, size // 10)
    bar_h = max(2, size // 14)
    draw.rounded_rectangle(
        (inner + size // 10, bar_y, size - inner - size // 10, bar_y + bar_h),
        radius=bar_h // 2,
        fill=ACCENT,
    )
    dot_r = max(2, size // 18)
    draw.ellipse(
        (size - inner - dot_r * 3, inner + dot_r, size - inner - dot_r, inner + dot_r * 3),
        fill=ACCENT2,
    )
    return img


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    master = render_icon(256)
    png_path = ASSETS / "oxco_icon.png"
    master.save(png_path, format="PNG")
    ico_path = ASSETS / "oxco_icon.ico"
    master_rgb = master.convert("RGBA")
    ico_path.write_bytes(b"")  # truncate before save
    master_rgb.save(
        ico_path,
        format="ICO",
        sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
    )
    embed_path = ROOT / "oxco_icon_embed.py"
    b64 = base64.b64encode(ico_path.read_bytes()).decode("ascii")
    embed_path.write_text(
        (
            '"""Auto-generated by scripts/make_oxco_icon.py — do not edit."""\n'
            "from __future__ import annotations\n\n"
            "import base64\n"
            "import tempfile\n"
            "from pathlib import Path\n\n"
            f'_ICON_B64 = "{b64}"\n\n\n'
            "def materialize_icon_ico() -> Path:\n"
            '    """Schreibt das eingebettete .ico nach %TEMP% (Fallback ohne assets/)."""\n'
            "    data = base64.b64decode(_ICON_B64)\n"
            '    dest = Path(tempfile.gettempdir()) / "oxco_app_icon.ico"\n'
            "    if not dest.is_file() or dest.read_bytes() != data:\n"
            "        dest.write_bytes(data)\n"
            "    return dest\n"
        ),
        encoding="utf-8",
    )
    print(f"Wrote {png_path}")
    print(f"Wrote {ico_path}")
    print(f"Wrote {embed_path}")


if __name__ == "__main__":
    main()
